### ISSUE TITLE
Keyring error on HXTool Settings

### ISSUE THREAD

**Issue by mathurin68** [fireeye/HXTool#75]
Error on adding background credentials in HXTool Settings - 
running the latest version of HXTool on WSL.  

`
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
`

**Comment by B0fH** [comment]
Hi @mathurin68  -
 I haven't tested HXTool on WSL, but my suspicion would be that it doesn't have access to the Windows Credential Locker because its a separate subsystem, while at the same time dbus isn't available. My suggestion would be to install a 3rd party credential storage provider for keyring, such as keyring.cryptfile. See https://github.com/jaraco/keyring#third-party-backends

Thanks,
 Elazar

**Comment by mathurin68** [comment]
Interesting...thank you!

**Comment by mathurin68** [comment]
Hmmm, I'm getting the same error on 

CentOS Linux release 7.9.2009 (Core)
python 3.8 (virtualenv)
